# This is the development configuration for the User Service.
eureka:
  client:
    service-url:
      # Change default-zone to defaultZone
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/

spring:
  application:
    name: USER-SERVICE
  docker:
    compose:
      enabled: true