# This is the development configuration for the Order Service.
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:admin}:${MONGODB_PASSWORD:password}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/order_db?authSource=admin
      auto-index-creation: true

  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
